version: "3.8"

services:

  # --- Budibase ---
  app-service:
    image: budibase/apps
    container_name: bbapps
    restart: unless-stopped
    networks: [default, bi_network]
    environment:
      SELF_HOSTED: 1
      COUCH_DB_URL: http://${COUCH_DB_USER}:${COUCH_DB_PASSWORD}@couchdb-service:5984
      WORKER_URL: http://worker-service:4003
      MINIO_URL: http://minio-service:9000
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      INTERNAL_API_KEY: ${INTERNAL_API_KEY}
      BUDIBASE_ENVIRONMENT: ${BUDIBASE_ENVIRONMENT}
      PORT: 4002
      API_ENCRYPTION_KEY: ${API_ENCRYPTION_KEY}
      JWT_SECRET: ${JWT_SECRET}
      LOG_LEVEL: info
      ENABLE_ANALYTICS: "true"
      REDIS_URL: redis-service:6379
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      BB_ADMIN_USER_EMAIL: ${BB_ADMIN_USER_EMAIL}
      BB_ADMIN_USER_PASSWORD: ${BB_ADMIN_USER_PASSWORD}
      PLUGINS_DIR: ${PLUGINS_DIR}
      OFFLINE_MODE: ${OFFLINE_MODE:-}
    depends_on: [worker-service, redis-service]

  worker-service:
    image: budibase/worker
    container_name: bbworker
    restart: unless-stopped
    networks: [default, bi_network]
    environment:
      SELF_HOSTED: 1
      PORT: 4003
      CLUSTER_PORT: ${MAIN_PORT}
      API_ENCRYPTION_KEY: ${API_ENCRYPTION_KEY}
      JWT_SECRET: ${JWT_SECRET}
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      MINIO_URL: http://minio-service:9000
      APPS_URL: http://app-service:4002
      COUCH_DB_USERNAME: ${COUCH_DB_USER}
      COUCH_DB_PASSWORD: ${COUCH_DB_PASSWORD}
      COUCH_DB_URL: http://${COUCH_DB_USER}:${COUCH_DB_PASSWORD}@couchdb-service:5984
      INTERNAL_API_KEY: ${INTERNAL_API_KEY}
      REDIS_URL: redis-service:6379
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      OFFLINE_MODE: ${OFFLINE_MODE:-}
    depends_on: [redis-service, minio-service]

  minio-service:
    image: minio/minio
    restart: unless-stopped
    networks: [default, bi_network]
    volumes:
      - minio_data:/data
    environment:
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      MINIO_BROWSER: "off"
    command: server /data --console-address ":9001"
    healthcheck:
      test: timeout 5s bash -c ':> /dev/tcp/127.0.0.1/9000' || exit 1
      interval: 30s
      timeout: 20s
      retries: 3

  proxy-service:
    image: budibase/proxy
    container_name: bbproxy
    restart: unless-stopped
    networks: [default, bi_network]
    ports:
      - ${MAIN_PORT}:10000
    environment:
      - PROXY_RATE_LIMIT_WEBHOOKS_PER_SECOND=10
      - PROXY_RATE_LIMIT_API_PER_SECOND=20
      - APPS_UPSTREAM_URL=http://app-service:4002
      - WORKER_UPSTREAM_URL=http://worker-service:4003
      - MINIO_UPSTREAM_URL=http://minio-service:9000
      - COUCHDB_UPSTREAM_URL=http://couchdb-service:5984
      - RESOLVER=127.0.0.11
    depends_on:
      - minio-service
      - worker-service
      - app-service
      - couchdb-service

  couchdb-service:
    image: budibase/couchdb:v3.3.3-sqs-v2.1.1
    restart: unless-stopped
    networks: [default, bi_network]
    environment:
      - COUCHDB_PASSWORD=${COUCH_DB_PASSWORD}
      - COUCHDB_USER=${COUCH_DB_USER}
      - TARGETBUILD=docker-compose
    volumes:
      - couchdb3_data:/opt/couchdb/data

  redis-service:
    image: redis
    restart: unless-stopped
    networks: [default, bi_network]
    command: redis-server --requirepass "${REDIS_PASSWORD}"
    volumes:
      - redis_data:/data

  # --- Основной BI проект ---
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_started
    environment:
      - DB_HOST=db
      - DB_NAME=BI
      - DB_USER=bitask_user
      - DB_PASS=bitask_pass
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USER=admin
      - RABBITMQ_PASS=mq_pass
    networks: [bi_network]
    restart: unless-stopped
  db:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=bitask_user
      - POSTGRES_PASSWORD=bitask_pass
      - POSTGRES_DB=BI
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bitask_user -d BI"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks: [bi_network]

  rabbitmq:
    image: rabbitmq:4-management
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=mq_pass
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks: [bi_network]

  runner:
    build: .
    command: python runner.py
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_started
    environment:
      - DB_HOST=db
      - DB_NAME=BI
      - DB_USER=bitask_user
      - DB_PASS=bitask_pass
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USER=admin
      - RABBITMQ_PASS=mq_pass
    networks: [bi_network]
    restart: unless-stopped

  # --- DAG сервис ---
#  ltv:
#    build: DAGs/LTV
#    depends_on:
#      db:
#        condition: service_healthy  # Ждём, пока PostgreSQL станет healthy
#      rabbitmq:
#        condition: service_started
#    environment:
#      - RESEARCH_PERIOD=90
#      - CURRDATE=2025-06-15
#      - SERVICE_NAME=LTV
#    volumes:
#      - ./result:/app/result
#    networks: [bi_network]
  ltv:
    extends:
      file: DAGs/LTV/docker-compose.yaml
      service: ltv
  lal:
    extends:
      file: DAGs/LAL/docker-compose.yaml
      service: lal


volumes:
  couchdb3_data:
  minio_data:
  redis_data:
  postgres_data:
  rabbitmq_data:

networks:
  bi_network:
    driver: bridge
    name: bi_network
    attachable: true
    labels:
      com.docker.compose.project: "bi_project"