services:
  ltv:
    build: .
    volumes:
      - ./result:/app/result
    networks:
      - bi_network  # Должна быть общая сеть с RabbitMQ

networks:
  bi_network:
    external: true  # Используем сеть из основного docker-compose