services:
  ltv:
    build: .
    environment:
      - RESEARCH_PERIOD=90
      - CURRDATE=2025-06-15
      - SERVICE_NAME=LTV  # Для имени очереди
    volumes:
      - ./result:/app/result
    networks:
      - bi_network  # Должна быть общая сеть с RabbitMQ

networks:
  bi_network:
    external: true  # Используем сеть из основного docker-compose